{% set name = "cosmopharm" %}
{% set version = "0.0.25" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/7d/d7/c55bf2c2f0815f87aaf0ec4544a52b5e54e3f01bffb5c7a1df6cdfef41fa/cosmopharm-0.0.25.tar.gz
  sha256: 023eec82fed4c9fa8f940f96f72cc61fb4e641c18c9b292351fc5f78a4312526

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.0
    - numpy >=1.15
    - pandas >=1.0
    - scipy >=1.4
    - openpyxl >=3.0

test:
  imports:
    - cosmopharm

about:
  home: "https://github.com/ivanantolo/cosmopharm"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Predictive modeling for drug-polymer compatibility in pharmaceutical formulations using COSMO-SAC."

extra:
  recipe-maintainers:
    - ivanantolo
