{% set name = "cosmopharm" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/4c/27/16716cfcdf52634bb1278f72c4a61c91fa921942416bfb5d355de38003cb/cosmopharm-0.0.1.tar.gz
  sha256: f0b65e9af75a718ad8639d3bedf2b12ee4099d9738c9d04bae9007df9a08f791

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.0
    - numpy >=1.15
    - pandas >=1.0
    - scipy >=1.4
    - openpyxl >=3.0

test:
  imports:
    - cosmopharm

about:
  home: "https://github.com/ivanantolo/cosmopharm"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Predictive modeling for drug-polymer compatibility in pharmaceutical formulations using COSMO-SAC."

extra:
  recipe-maintainers:
    - ivanantolo
