{% set name = "cosmopharm" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/e8/1f/ea465d9f34dff2b5f17a40c95b2b5e6b01660610f3cf81e5a8107f2aa014/cosmopharm-{{ version }}.tar.gz
  sha256: 35af55fbe5f4fb9894f121d3e3512a484a38ecb98a252bf60b50127edd72bcb4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.0
    - numpy >=1.15
    - pandas >=1.0
    - scipy >=1.4
    - openpyxl >=3.0

test:
  imports:
    - cosmopharm

about:
  home: "https://github.com/ivanantolo/cosmopharm"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Predictive modeling for drug-polymer compatibility in pharmaceutical formulations using COSMO-SAC."

extra:
  recipe-maintainers:
    - ivanantolo
